apiVersion: crds.driscoll.co/v1
kind: OpSecret
metadata:
  name: grafana-credentials-metrics
spec:
  last-updated: "{{ now | date "2006-01-02T15:04:05Z07:00" }}"
  source:
    vault: Cluster
    item: Grafana Cloud
    section: Metrics
  secret:
    name: grafana-credentials-metrics
    namespaces:
      - {{ .Release.Namespace }}
    secret-type: basic
    refresh-seconds: 120
    keys:
      - from: UserId
        to: userId
      - from: AccessToken
        to: accessToken