apiVersion: crds.driscoll.co/v1
kind: OpSecret
metadata:
  name: grafana-credentials-profiler
spec:
  last-updated: "{{ now | date "2006-01-02T15:04:05Z07:00" }}"
  source:
    vault: Cluster
    item: Grafana Cloud
    section: Profiler
  secret:
    name: grafana-credentials-profiler
    namespaces:
      - {{ .Release.Namespace }}
    secret-type: basic
    refresh-seconds: 120
    keys:
      - from: Host
        to: host
      - from: UserId
        to: userId
      - from: Read Token
        to: readToken
      - from: Write Token
        to: writeToken