apiVersion: crds.driscoll.co/v1
kind: OpSecret
metadata:
  name: grafana-credentials-traces
spec:
  last-updated: "{{ now | date "2006-01-02T15:04:05Z07:00" }}"
  source:
    vault: Cluster
    item: Grafana Cloud
    section: Traces
  secret:
    name: grafana-credentials-traces
    namespaces:
      - {{ .Release.Namespace }}
    secret-type: basic
    refresh-seconds: 120
    keys:
      - from: AuthKey
        to: authKey