name: Checks

on:
  push:
    branches-ignore:
      - main

env:
  codeCoverageMinimum: 0

jobs:
  code-formatting:
    name: Formatting
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Formatting Check
        run: make check-formatting
  run-go-vet:
    name: Go Vet
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Go Vet
        run: make govet
  code-linting:
    name: Linting
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Linting
        run: make lint
  test-coverage:
    name: Test Coverage
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Test Coverage
        run: make coverage
  run-go-unit-tests:
    name: Unit Tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Unit Tests
        run: make test
